output "application_id" {
  description = "The resource ID of the application for which this password should be created"
  value       = azuread_application_password.this.application_id
}

output "display_name" {
  description = "A display name for the password"
  value       = azuread_application_password.this.display_name
}

output "end_date" {
  description = "The end date until which the password is valid, formatted as an RFC3339 date string (e.g. `2018-01-01T01:02:03Z`)"
  value       = azuread_application_password.this.end_date
}

output "id" {
  value = azuread_application_password.this.id
}

output "key_id" {
  description = "A UUID used to uniquely identify this password credential"
  value       = azuread_application_password.this.key_id
}

output "rotate_when_changed" {
  description = "Arbitrary map of values that, when changed, will trigger rotation of the password"
  value       = azuread_application_password.this.rotate_when_changed
}

output "start_date" {
  description = "The start date from which the password is valid, formatted as an RFC3339 date string (e.g. `2018-01-01T01:02:03Z`). If this isn't specified, the current date is used"
  value       = azuread_application_password.this.start_date
}

output "value" {
  description = "The password for this application, which is generated by Azure Active Directory"
  value       = azuread_application_password.this.value
  sensitive   = true
}
